apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Admin-группа может всё
    p, role:platform-admin, *, *, */*, allow
    g, platform-team, role:platform-admin

    # Платформенная команда видит только platform-project
    p, role:platform-viewer, applications, get, platform/*, allow
    p, role:platform-viewer, applications, sync, platform/*, allow
    g, platform-devs, role:platform-viewer