apiVersion: v1
kind: Secret
metadata:
  name: cluster-target
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: dev
    region: local
stringData:
  name: target-cluster
  server: https://172.20.0.6:6443
  config: |
    {
      "bearerToken": "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltY3pTa05GVVV4dU5rVkRXbkExZUZRMk5WQmZNblpXTmpWWll6VjNhbEZJYWxkUlVUVmpTR3hoZWswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKaGNtZHZZMlF0YldGdVlXZGxjaTEwYjJ0bGJpSXNJbXQxWW1WeWJtVjBaWE11YVc4dmMyVnlkbWxqWldGalkyOTFiblF2YzJWeWRtbGpaUzFoWTJOdmRXNTBMbTVoYldVaU9pSmhjbWR2WTJRdGJXRnVZV2RsY2lJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExuVnBaQ0k2SW1VelptWmhOV1F3TFdaak4yTXRORE5tWlMwNU9UQmxMVEpqT1dOaFlqaG1PRGN4TVNJc0luTjFZaUk2SW5ONWMzUmxiVHB6WlhKMmFXTmxZV05qYjNWdWREcHJkV0psTFhONWMzUmxiVHBoY21kdlkyUXRiV0Z1WVdkbGNpSjkuZ3Y0MzZ1aDF4UDl5RVVSUmg5WU9yM3ZkcmZDOGZ1VHM0ZzZlLTUydE05RVFla0tXTEVOSl8zdU5XOGZmUzJOUUsxa2RrTEwwZ21NZnViQnpRTUQwZDJ3ejFMWm80UDBkbjFtYThpSHh6RGJNM3U4dEVBcjR3aXZ0VmVhdDZmeGxpcGNpOWU1b1BUZUtQeGRVU0ZvMXJRN0RBeUFNMTVILVExVVZudElnMDBsMWZILVRQSDJwcG9aLTlsOUxZX09obWNzVlhlZ0h5TmRHSFVsVVR0QjZidVNjTThxT0F4Y0J5YzZoa0g2aGd0RnEzQ1RpUklDRXZNMXZHSEtxamNQWlF4Q1ZQY2RRdGM4Z3VnUzF0VnFYRDZlUHRIRlhKWERFbWdXY0VVRm9xUkw3U3Bhd05MMWVrQlNNMjg2N3V4anNvNjZDa2trTG5McTNJTkFTbWZibHdB",
      "tlsClientConfig": { "insecure": true }
    }