apiVersion: v1
kind: Secret
metadata:
  name: cluster-target
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    env: dev
    region: local
stringData:
  name: target-cluster
  server: https://172.20.0.6:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImczSkNFUUxuNkVDWnA1eFQ2NVBfMnZWNjVZYzV3alFIaldRUTVjSGxhek0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcmdvY2QtbWFuYWdlci10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QtbWFuYWdlciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImUzZmZhNWQwLWZjN2MtNDNmZS05OTBlLTJjOWNhYjhmODcxMSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphcmdvY2QtbWFuYWdlciJ9.gv436uh1xP9yEURRh9YOr3vdrfC8fuTs4g6e-52tM9EQekKWLENJ_3uNW8ffS2NQK1kdkLL0gmMfubBzQMD0d2wz1LZo4P0dn1ma8iHxzDbM3u8tEAr4wivtVeat6fxlipci9e5oPTeKPxdUSFo1rQ7DAyAM15H-Q1UVntIg00l1fH-TPH2ppoZ-9l9LY_OhmcsVXegHyNdGHUlUTtB6buScM8qOAxcByc6hkH6hgtFq3CTiRICEvM1vGHKqjcPZQxCVPcdQtc8gugS1tVqXD6ePtHFXJXDEmgWcEUFoqRL7SpawNL1ekBSM2867uxjso66CkkkLnLq3INASmfblwA",
      "tlsClientConfig": { "insecure": true }
    }