apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform team services
  sourceRepos:
    - '*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
    - server: https://172.20.0.6:6443
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'